[workspace]
members = ["day*"]
resolver = "2"

[workspace.dependencies]
indicatif = "0.17"
nom = "7"
rayon = "1.8"

[workspace.lints.clippy]
# Groups
all = "warn"
pedantic = "warn"
# Individual lints
wildcard_imports = { level = "allow", priority = 2 }
