[package]
name = "day05"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "main.rs"

[lints]
workspace = true

[dependencies]
indicatif = { workspace = true, features = ["rayon"] }
nom.workspace = true
rayon.workspace = true
